### ISSUE TITLE
How to customize fromNow output ?

### ISSUE THREAD

**Issue by MrBillium** [miguelgrinberg/Flask-Moment#25] opened 2016-10-27 16:49 UTC
I am displaying time data was received  using flask Moment.fromNow.  Typically it outputs 'a few seconds ago' but sometimes the sender's clock is a little off and it displays ' in a few seconds' - which makes no sense to the user.
To fix this I want to change ' in a few seconds' to 'current'  but this does not seem easy using Moment customization so I thought I could simply change the output in jinja2 but cannot see how to capture the output string to change it:
Code:
 {% set moment_text = moment(value.lastupdated).fromNow(no_suffix = False) %}

```
    {% if moment_text == "in a few seconds"  %}
        {% set moment_text = "current" %}
    {% endif %}
```

This never fires because moment_text is still a date and not a string. 
How can I get the output string of Flask Moment so I can test it and change it?
Thanks
Bill

**Comment by miguelgrinberg** [comment] 2016-10-27 17:54
This is a tricky issue to handle. The problem is that the timestamps are generated using the server's clock, but moment renders them using the clock on the client.

The typical solution is for either the client or the server to figure out what is the time difference with the other party, and then adjust the time so that the client always has it relative to its own clock. This could be an interesting feature enhancement for this extension, actually, but right now there is no support to do something like this.

You could have the client send its clock to the server via an ajax call when the page loads, and that will enable the server to adjust all timestamps for that client.

The solution that you propose can be implemented if you were working directly with moment in JavaScript, but all that is handled by Flask-Moment, so you have no easy access, unfortunately.

**Comment by MrBillium** [comment] 2016-10-27 19:15
I was hoping there was a way to cause Flask Moment to output the final string into another variable
something like    {{ Set moment_textoutput = moment_text.to_string() }}

Then I would have a text variable that I could manipulate

**Comment by miguelgrinberg** [comment] 2016-10-27 20:45
Flask-Moment does not generate the formatted date. All Flask-Moment does is generate the right JavaScript to render the date in the client. The time adjustment can be done in the server before rendering the template, but for that you need the client to have passed its current time in advance, so that the server can calculate an estimated time difference. It can also be done in the client if the server passes its time to it, so then the client calculates the difference and adjusts the time before passing it to moment.js. Unfortunately this last option can be implemented only if you write your own JavaScript, not if you let Flask-Moment autogenerate the JS.

**Comment by valentin-ballester** [comment] 2019-06-07 06:37
Hello, im having kinda the same issue, i solve it resolving that initially i need to send the time difference with the closest datetime i can get from the present (the present is when the page loads, then i use refresh function), so in the route i create a:

`...
render_template(... , now=datetime.utcnow())`

and then use it with flask-moment 

`moment(stored_date).fromTime(now, refresh=True)`

why dont do this instead of the ajax ?

**Comment by valentin-ballester** [comment] 2019-06-07 07:12
Hello, im having the same problem. cant the flask moment from_now being considered as a bug ? because i only dicovered this problem after many testings, and it could get my users lost. for the moment i disabled the subfix and i add it manually, it solves the problem but it is kinda hacking and i lost the possibility of using the full capability of moment, if i decided in the future to add a feature to schedule my orders, and i want moment to detect what subfix to use ? i cant because of this bug, i probably should the ajax alternative or i dont know what other alternatives i have.

**Comment by miguelgrinberg** [comment] 2019-06-07 09:05
@valentin-ballester why do you attribute the bug to Flask-Moment? This problem is very common and affects any two systems that have clocks out of sync. If you generate a time in one of the system (server) and then pass it to the other (client) for rendering you are bound to have problems. It has nothing to do with Flask-Moment.

**Comment by miguelgrinberg** [comment] 2021-06-07 22:51
I don't believe I'll ever have time to dedicate to this issue, which is extremely complex, so for now I'm going to close. The recommendation is that you make sure that the clocks are relatively close. If you want to make sure "in a few seconds" does not appear you can always add a few seconds to the times that you render.

**Closed by miguelgrinberg** 2021-06-07 22:51 UTC
Labels: enhancement
